title: <p align="center">Suma Santosh</p>
logo: /assets/img/mylogo.png
description: <p align="center">
<br>
I have worked on Mobile Apps and Framework for 12 years, My experience varies from being team member to building teams, ramping up team on new technologies, building products based on specification or customer requirement<br>
</p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
